C_SOURCES += \
lwip-1.4.1/src/core/def.c \
lwip-1.4.1/src/core/dhcp.c \
lwip-1.4.1/src/core/dns.c \
lwip-1.4.1/src/core/init.c \
lwip-1.4.1/src/core/mem.c \
lwip-1.4.1/src/core/memp.c \
lwip-1.4.1/src/core/netif.c \
lwip-1.4.1/src/core/pbuf.c \
lwip-1.4.1/src/core/raw.c \
lwip-1.4.1/src/core/stats.c \
lwip-1.4.1/src/core/sys.c \
lwip-1.4.1/src/core/tcp_in.c \
lwip-1.4.1/src/core/tcp_out.c \
lwip-1.4.1/src/core/tcp.c \
lwip-1.4.1/src/core/timers.c \
lwip-1.4.1/src/core/udp.c \
lwip-1.4.1/src/core/ipv4/autoip.c \
lwip-1.4.1/src/core/ipv4/icmp.c \
lwip-1.4.1/src/core/ipv4/igmp.c \
lwip-1.4.1/src/core/ipv4/inet_chksum.c \
lwip-1.4.1/src/core/ipv4/inet.c \
lwip-1.4.1/src/core/ipv4/ip_addr.c \
lwip-1.4.1/src/core/ipv4/ip_frag.c \
lwip-1.4.1/src/core/ipv4/ip.c \
lwip-1.4.1/src/netif/etharp.c \
lwip-1.4.1/src/netif/ethernetif.c \
lwip-1.4.1/src/netif/slipif.c

C_INCLUDES += \
-Ilwip-1.4.1/src/include \
-Ilwip-1.4.1/src/include/arch \
-Ilwip-1.4.1/src/include/ipv4 \

