C_SOURCES += \
FreeRTOS-Kernel/croutine.c \
FreeRTOS-Kernel/event_groups.c \
FreeRTOS-Kernel/list.c \
FreeRTOS-Kernel/queue.c \
FreeRTOS-Kernel/stream_buffer.c \
FreeRTOS-Kernel/tasks.c \
FreeRTOS-Kernel/timers.c \
\
FreeRTOS-Kernel/portable/GCC/ARM9_s3c2440/port.c \
FreeRTOS-Kernel/portable/GCC/ARM9_s3c2440/portISR.c \
\
FreeRTOS-Kernel/portable/MemMang/heap_4.c

C_INCLUDES += \
-IFreeRTOS-Kernel/include \
-IFreeRTOS-Kernel/portable/GCC/ARM9_s3c2440

