# TODO: 缺少timers.c文件 与lwip中文件重名 待解决 croutine.c 和 stream_buffer.c 不知道干什么用的,先不添加
C_SOURCES += \
FreeRTOS-Kernel/event_groups.c \
FreeRTOS-Kernel/list.c \
FreeRTOS-Kernel/queue.c \
FreeRTOS-Kernel/tasks.c \
FreeRTOS-Kernel/timers.c \
\
FreeRTOS-Kernel/portable/GCC/ARM9_s3c2440/port.c \
FreeRTOS-Kernel/portable/GCC/ARM9_s3c2440/portISR.c \
\
FreeRTOS-Kernel/portable/MemMang/heap_4.c

C_INCLUDES += \
-IFreeRTOS-Kernel/include \
-IFreeRTOS-Kernel/portable/GCC/ARM9_s3c2440

